export {default as Cart_Close_Btn} from "./Buttons/Close-Cart-Btn";
export {default as Proceed_To_Checkout_Btn} from "./Buttons/Proceed-To-Checkout-Btn";
export {default as ClientReviewSection} from "./sections/reviews/goto-section-Testimonials";
export {default as SpecialTraits} from "./sections/specialtraits/goto-section-specialTraits";
export {default as Footer_Section} from "./sections/footer/goto-section-footer";
export {default as BetterPricingSection} from "./sections/betterpricing/goto-section-betterPricing";
export {default as Cookies} from "./cookies/cookie";
export {default as DiscountCoupanPopup} from "./Popups/modal";
export {default as HeroBanner} from './sections/banner/banner';
export {default as ProductSpecification} from './sections/productcards/card';
export {default as OurStory} from './sections/ourstory/story';
export {default as GroupBuying} from './sections/groupbuying/groupbuy';
export {default as GoogleMapAddress} from './sections/googlemap/googlemap'